# Generated by Django 6.0.8 on 2026-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('paper', 'Research Paper'), ('documentation', 'Documentation'), ('tutorial', 'Tutorial'), ('video', 'Video'), ('course', 'Course')], max_length=30)),
                ('source_url', models.URLField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type'], name='knowledge_k_resourc_915dd6_idx'), models.Index(fields=['is_active'], name='knowledge_k_is_acti_3dd5a3_idx'), models.Index(fields=['-created_at'], name='knowledge_k_created_5d8cc0_idx')],
            },
        ),
    ]
